# Generated by Django 3.2 on 2021-04-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pic',
            new_name='Image',
        ),
    ]
