# Generated by Django 3.2 on 2021-04-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='abc@mail.com', max_length=50),
        ),
    ]
