# Generated by Django 3.2 on 2021-04-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210412_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='UserName',
        ),
    ]
